apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: grafana-system
spec:
  ports:
  - name: http-web
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.11.141
